[package]
name = "datagov-data"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
datagov-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
csv = { workspace = true }
parquet = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
